services:
  app-1:
    build: .
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: 100k
      MINI_SECKILL_WORKER_ID: 0
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mini_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: miniseckill
      SPRING_DATASOURCE_PASSWORD: miniseckill
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - rabbitmq

  app-2:
    build: .
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: 100k
      MINI_SECKILL_WORKER_ID: 1
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mini_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: miniseckill
      SPRING_DATASOURCE_PASSWORD: miniseckill
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - redis
      - rabbitmq

  app-3:
    build: .
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: 100k
      MINI_SECKILL_WORKER_ID: 2
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mini_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: miniseckill
      SPRING_DATASOURCE_PASSWORD: miniseckill
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - redis
      - rabbitmq

  app-4:
    build: .
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: 100k
      MINI_SECKILL_WORKER_ID: 3
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mini_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: miniseckill
      SPRING_DATASOURCE_PASSWORD: miniseckill
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8083:8080"
    depends_on:
      - mysql
      - redis
      - rabbitmq
