package com.example.miniseckill.mapper;

import com.example.miniseckill.entity.CompensationRecord;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

/**
 * Mapper for compensation records generated by reconcile and replay paths.
 */
@Mapper
public interface CompensationRecordMapper {

    @Insert("""
            INSERT INTO seckill_compensation (request_id, activity_id, sku_id, type, status, detail, created_at, updated_at)
            VALUES (#{requestId}, #{activityId}, #{skuId}, #{type}, #{status}, #{detail}, NOW(), NOW())
            """)
    int insert(CompensationRecord record);

    @Select("""
            SELECT id, request_id, activity_id, sku_id, type, status, detail, created_at, updated_at
            FROM seckill_compensation
            ORDER BY id DESC
            LIMIT #{limit}
            """)
    List<CompensationRecord> selectRecent(@Param("limit") int limit);
}
